services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: filestorage_sqlserver
    environment:
      SA_PASSWORD: "YourStrong@Password123"
      MSSQL_SA_PASSWORD: "YourStrong@Password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong@Password123 -Q 'SELECT 1' -C || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 20
    restart: always

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    init: true
    container_name: filestorage_api
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=FileStorageDb;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True;"
    ports:
      - "5015:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    restart: on-failure
    volumes:
      - ./_storage:/app/_storage  # Mount local storage for persistence

  webui:
    image: ${DOCKER_REGISTRY-}webui
    build:
      context: src/file-storage-ui
      dockerfile: Dockerfile
    init: true
    container_name: filestorage_ui
    ports:
      - "4200:80"
    depends_on:
      - api

volumes:
  mssqldata:
  