

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: filestorage_sqlserver
    environment:
      SA_PASSWORD: "shana123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql
    restart: always

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    container_name: filestorage_api
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: >
        Server=sqlserver;
        Database=FileStorageDb;
        User Id=shana;
        Password=shana123;
        TrustServerCertificate=True;
    ports:
      - "5015:8080"
    depends_on:
      - sqlserver


volumes:
  mssqldata: